#! /usr/bin/env node

var fs = require('fs');

function get(req,res){
    if(req.url === '/'){
        var path = './view/html/home.html';
        loadFile(path,req,res);

    }
}

function loadFile(path,req,res){
    var headers = {'Content-Type': 'text/html; charset=utf-8'};
    fs.readFile(path,(err,data)=>{
        if(!err){
            res.writeHead(200,headers);
            res.write(data);
        }
        else{
            console.log(err);
            res.writeHead(404);
        }

        res.end();
    })
}

module.exports = get;